"""The project profile: what aidlc believes about a repository.

The profile is generated by detection and **committed** to the consumer repo.
Committing it is a deliberate choice with a real trade-off:

* It drives *local* tooling as well as CI, and a CI-time detection can never
  serve the local side.
* A profile change appearing in a pull-request diff is a useful review signal;
  "this PR quietly added a language" is worth seeing.
* The cost is staleness, which is why `aidlc check --profile` re-detects and
  compares. That check is not optional.

Everything here is data. No method on these models touches the filesystem.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

#: Bumped only on a breaking change to the profile shape. `aidlc` refuses to
#: read a profile from a future schema rather than guessing at its meaning.
PROFILE_SCHEMA_VERSION = 1


class Strict(BaseModel):
    """Base model that rejects unknown fields.

    A silently-dropped key in a generated file is a bug that surfaces days
    later as "why did that setting do nothing". Fail at parse time instead.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)


class SetupKind(StrEnum):
    """Which toolchain the CI job installs before running steps.

    `NONE` is the escape hatch: the target declares its own commands and aidlc
    installs nothing. It is what makes any language usable immediately, with no
    adapter written.
    """

    NONE = "none"
    UV = "uv"
    NODE = "node"
    JAVA = "java"
    GO = "go"
    RUST = "rust"
    DOTNET = "dotnet"


class StepName(StrEnum):
    """The fixed vocabulary of build steps.

    Deliberately small and closed. Every ecosystem maps onto these six, and a
    closed set is what lets one generic CI workflow serve all of them.
    """

    INSTALL = "install"
    LINT = "lint"
    FORMAT = "format"
    TYPECHECK = "typecheck"
    TEST = "test"
    BUILD = "build"


class StepSource(StrEnum):
    """Where a step's command came from.

    Surfaced by `aidlc explain steps`. The distinction matters because the
    governing rule is that a project's own declarations beat our opinions, and
    you should be able to see that rule being applied.
    """

    PROJECT = "project"
    """Declared by the repo itself: an npm script, a Makefile target, a task."""

    DEFAULT = "default"
    """The adapter's opinion, used because the project said nothing."""

    CONFIG = "config"
    """Written explicitly in `.aidlc/config.yml`; beats both of the above."""


class Step(Strict):
    """One command, and the reason it is the command."""

    name: StepName
    command: str
    source: StepSource


class JobSpec(Strict):
    """Everything the generic CI workflow needs to build one target.

    This is the whole interface between an ecosystem adapter and the CI layer.
    Keeping it plain data is what allows a single `reusable-lang-ci.yml` to
    serve every language instead of one workflow per ecosystem.
    """

    setup: SetupKind
    versions: list[str] = Field(default_factory=list)
    """Toolchain versions to run as a matrix. Empty means the runner default."""

    cache_dependency_glob: str | None = None
    """Lockfile path the setup action keys its cache on."""

    working_directory: str = "."
    steps: list[Step] = Field(default_factory=list)

    def step(self, name: StepName) -> Step | None:
        return next((s for s in self.steps if s.name is name), None)


class Target(Strict):
    """One buildable unit inside a repository.

    A repo with a Python service and a React front end has two targets. A
    single-package repo has one, at path ".".
    """

    path: str
    ecosystem: str
    """The adapter that claimed this target, e.g. "python", "node", "jvm"."""

    languages: list[str] = Field(default_factory=list)
    manager: str | None = None
    """Package manager in use: uv, pnpm, maven, cargo, and so on."""

    frameworks: list[str] = Field(default_factory=list)
    """Detected framework hints. These select rule packs; they never alter CI."""

    facts: dict[str, Any] = Field(default_factory=dict)
    """Ecosystem-specific evidence. Free-form because adapters differ, and
    surfaced verbatim by `aidlc explain`."""

    job: JobSpec


class Conflict(Strict):
    """Something aidlc found and deliberately refused to touch."""

    kind: str
    path: str
    note: str


class VcsInfo(Strict):
    host: str | None = None
    repo: str | None = None
    """In `owner/name` form when it can be determined."""


class Profile(Strict):
    """The committed detection result for one repository."""

    schema_version: int = Field(default=PROFILE_SCHEMA_VERSION, alias="schema")
    generated_by: str
    root: str = "."
    vcs: VcsInfo = Field(default_factory=VcsInfo)
    targets: list[Target] = Field(default_factory=list)
    packs_selected: list[str] = Field(default_factory=list)
    conflicts: list[Conflict] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid", frozen=True, populate_by_name=True)

    @property
    def ecosystems(self) -> list[str]:
        """Distinct ecosystems present, in first-seen order."""
        seen: dict[str, None] = {}
        for target in self.targets:
            seen.setdefault(target.ecosystem, None)
        return list(seen)
