"""Generating the caller workflow a consumer repository commits.

The caller is deliberately tiny. Everything that could change lives in the
platform repository, so a consumer picks up fixes by a tag moving rather than
by regenerating anything.

Two details are load-bearing:

* The caller declares its own ``permissions``. A called workflow can only ever
  *reduce* what it was given, so the platform cannot grant itself anything and
  the grant has to happen here.
* The platform ref is pinned to a major tag. Consumers get patches
  automatically and are never broken by a new major.
"""

from __future__ import annotations

from aidlc.render.emitters import Artifact, ArtifactKind

#: The platform repository. Consumers reference it by this name, so it is the
#: one value that must change if the project is ever forked or renamed.
PLATFORM_REPO = "jameslevine/ai-dlc"

#: Major tag consumers pin to. Moving this in a consumer is the deliberate act
#: of accepting a breaking change; see VERSIONING.md.
PLATFORM_REF = "v1"

WORKFLOW_PATH = ".github/workflows/aidlc.yml"


def caller_workflow(*, strictness: str = "standard") -> str:
    return f"""\
# Generated by aidlc. Do not edit; run `aidlc sync` instead.
#
# Everything this runs is defined in {PLATFORM_REPO}. To change what CI does,
# edit .aidlc/config.yml or your project's own scripts and re-run `aidlc sync`.
name: aidlc

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# Cancel superseded runs on the same ref. A queue of stale runs on a branch
# someone is actively pushing to wastes minutes and tells you nothing.
concurrency:
  group: aidlc-${{{{ github.ref }}}}
  cancel-in-progress: true

# Declared here because permissions can only be reduced down a call chain,
# never raised. The platform workflow cannot grant itself anything.
permissions:
  contents: read

jobs:
  ci:
    uses: {PLATFORM_REPO}/.github/workflows/aidlc-ci.yml@{PLATFORM_REF}
    with:
      strictness: {strictness}
"""


def workflow_artifact(*, strictness: str = "standard") -> Artifact:
    return Artifact(
        path=WORKFLOW_PATH,
        kind=ArtifactKind.FILE,
        content=caller_workflow(strictness=strictness),
    )
